name: Langulus::Anyness CI
on: [push, pull_request] # Trigger on pushes to all branches and for all pull-requests

jobs:
  build:
    strategy:
      fail-fast: false # do not abort on a failed job
      matrix:
        os: [ubuntu-22.04, windows-latest]
        build: [Debug, Release]
        architecture: [x86, x64]
        managed: ['-DLANGULUS_FEATURE_MANAGED_MEMORY=OFF', '-DLANGULUS_FEATURE_MANAGED_MEMORY=ON']
        cxx: [g++, clang++, cl]
        exclude:
          - os: ubuntu-22.04
            cxx: cl
          - os: ubuntu-22.04
            architecture: x86
          - os: windows-latest
            cxx: g++
          - os: windows-latest
            cxx: clang++
        include:
          #- os: ubuntu-22.04
          #  architecture: x86
          #  cmake_args: "-DCMAKE_CXX_FLAGS=-m32"
          - os: ubuntu-22.04
            architecture: x64
            cmake_args: "-DCMAKE_CXX_FLAGS=-m64"
          - os: windows-latest
            architecture: x86
            cmake_args: "-G \"Visual Studio 17 2022\" -A Win32"
          - os: windows-latest
            architecture: x64
            cmake_args: "-G \"Visual Studio 17 2022\" -A x64"
          - managed: '-DLANGULUS_FEATURE_MANAGED_MEMORY=OFF'
            suffix: ''
          - managed: '-DLANGULUS_FEATURE_MANAGED_MEMORY=ON'
            suffix: '-managed'

    name: "${{matrix.os}}-${{matrix.cxx}}-${{matrix.build}}-${{matrix.architecture}}${{matrix.suffix}}"
    runs-on: ${{matrix.os}}
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Configure
        run: cmake -DCMAKE_CXX_COMPILER=${{matrix.cxx}} -S . -B out/${{matrix.name}} -DCMAKE_BUILD_TYPE=${{matrix.build}} ${{matrix.cmake_args}} ${{matrix.managed}} -DLANGULUS_ENABLE_SAFE_MODE=ON
      - name: Build
        run: cmake --build out/${{matrix.name}} --config ${{matrix.build}}
      - name: Test
        run: cd out/${{matrix.name}} && ctest -V -C ${{matrix.build}}