name: Langulus::Anyness CI
on: [push, pull_request, repository_dispatch] # Trigger on pushes to all branches and for all pull-requests

jobs:
  build:
    strategy:
      fail-fast: false # do not abort on a failed job
      matrix:
        os: [ubuntu-22.04, windows-latest]
        build: [Debug, Release]
        arch: [x86, x64]
        managed: [ON, OFF]
        cxx: [g++, clang++, cl]
        exclude:
          - os: ubuntu-22.04
            cxx: cl
          - os: ubuntu-22.04
            arch: x86
          - os: windows-latest
            cxx: g++
          - os: windows-latest
            cxx: clang++
        include:
          #- os: ubuntu-22.04
          #  architecture: x86
          #  cmake_args: "-DCMAKE_CXX_FLAGS=-m32"
          - os: ubuntu-22.04
            arch: x64
            cmake_args: "-DCMAKE_CXX_FLAGS=-m64"
          - os: windows-latest
            arch: x86
            cmake_args: "-G \"Visual Studio 17 2022\" -A Win32"
          - os: windows-latest
            arch: x64
            cmake_args: "-G \"Visual Studio 17 2022\" -A x64"
          - managed: OFF
            suffix: ''
          - managed: ON
            suffix: '-managed'


    name: "${{matrix.os}}-${{matrix.cxx}}-${{matrix.build}}-${{matrix.arch}}${{matrix.suffix}}"
    runs-on: ${{matrix.os}}
    steps:
      - name: Dispatch Trigger
        if: ${{ startsWith(github.event.action, 'Dependency') }}
        run: >
          echo "Triggered by dependency: ${{github.event.client_payload.cause}}"
      - name: Clone
        uses: actions/checkout@v3
      - name: Configure
        run: >
          cmake
          -DCMAKE_CXX_COMPILER=${{matrix.cxx}}
          -S .
          -B out
          -DCMAKE_BUILD_TYPE=${{matrix.build}}
          -DLANGULUS_FEATURE_MANAGED_MEMORY=${{matrix.managed}}
          -DLANGULUS_FEATURE_MANAGED_REFLECTION=${{matrix.managed}}
          -DLANGULUS_ENABLE_TESTING=ON
          -DLANGULUS_BUILD_SHARED_LIBRARIES=ON
          ${{matrix.cmake_args}}
      - name: Build
        run: cmake --build out --config ${{matrix.build}}
      - name: Test
        run: cd out && ctest -V -C ${{matrix.build}}