name: Langulus::Anyness CI
on: [push, pull_request] # Trigger on pushes to all branches and for all pull-requests

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false # do not abort on a failed job
      matrix:
        config:
        - {
            # GCC 11 is the minimum required compiler, and comes with Ubuntu 22.04
            name: "Linux-GCC-11-Debug", artifact: "Linux.tar.xz",
            os: ubuntu-22.04,
            build_type: Debug,
            cc: "gcc", cxx: "g++",
            cmake_args: ""
          }
        - {
            # GCC 11 is the minimum required compiler, and comes with Ubuntu 22.04
            name: "Linux-GCC-11-Release", artifact: "Linux.tar.xz",
            os: ubuntu-22.04,
            build_type: RelWithDebInfo,
            cc: "gcc", cxx: "g++",
            cmake_args: ""
          }
        - {
            # Clang 11 is the minimum required compiler, and comes with Ubuntu 22.04
            name: "Linux-Clang-11-Debug", artifact: "Linux.tar.xz",
            os: ubuntu-22.04,
            build_type: Debug,
            cc: "clang", cxx: "clang++",
            cmake_args: ""
          }
        - {
            # Clang 11 is the minimum required compiler, and comes with Ubuntu 22.04
            name: "Linux-Clang-11-Release", artifact: "Linux.tar.xz",
            os: ubuntu-22.04,
            build_type: RelWithDebInfo,
            cc: "clang", cxx: "clang++",
            cmake_args: ""
          }
        - {
            name: "Windows-MSVC-2022-Debug-x64", artifact: "Windows-MSVC-x64.tar.xz",
            os: windows-latest,
            build_type: Debug,
            cc: "cl", cxx: "cl",
            cmake_args: "-G \"Visual Studio 17 2022\" -A x64",
          }
        - {
            name: "Windows-MSVC-2022-Release-x64", artifact: "Windows-MSVC-x64.tar.xz",
            os: windows-latest,
            build_type: RelWithDebInfo,
            cc: "cl", cxx: "cl",
            cmake_args: "-G \"Visual Studio 17 2022\" -A x64",
          }
        - {
            name: "Windows-MSVC-2022-Debug-x86", artifact: "Windows-MSVC-x86.tar.xz",
            os: windows-latest,
            build_type: Debug,
            cc: "cl", cxx: "cl",
            cmake_args: "-G \"Visual Studio 17 2022\" -A Win32",
          }
        - {
            name: "Windows-MSVC-2022-Release-x86", artifact: "Windows-MSVC-x86.tar.xz",
            os: windows-latest,
            build_type: RelWithDebInfo,
            cc: "cl", cxx: "cl",
            cmake_args: "-G \"Visual Studio 17 2022\" -A Win32",
          }
        # Consider adding these when Apple fix their shit
        #- {
        #    name: "macOS-Clang-Debug", artifact: "macOS.tar.xz",
        #    os: macos-latest,
        #    build_type: Debug,
        #    cc: "clang", cxx: "clang++",
        #    cmake_args: ""
        #  }
        #- {
        #    name: "macOS-Clang-Release", artifact: "macOS.tar.xz",
        #    os: macos-latest,
        #    build_type: RelWithDebInfo,
        #    cc: "clang", cxx: "clang++",
        #    cmake_args: ""
        #  }

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Configure
        run: cmake -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} -S . -B out/${{ matrix.config.name }} -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} ${{ matrix.config.cmake_args }}
      - name: Build
        run: cmake --build out/${{ matrix.config.name }} --config ${{ matrix.config.build_type }}
      - name: Test
        run: ctest --output-on-failure
